spring.application.name=traceusage-demo-api
server.port=8081

traceusage.enabled=true
traceusage.server-url=http://localhost:8080
traceusage.api-key=tru_sk_tPIsVAS7KmK41M1zkABkqLzPG7NUrO9tUUASm4tvF7o
traceusage.batch-size=100
traceusage.queue-capacity=10000
traceusage.max-retries=3
traceusage.retry-delay-millis=1000
