spring.application.name=traceusage-demo-api
server.port=8081

traceusage.enabled=true
traceusage.server-url=http://localhost:8080
traceusage.api-key=tru_sk_npFiQ8Bu3RN1EByy2amHQ5JeWyWSE2PJCyE_SXz29Vs
traceusage.batch-size=100
traceusage.queue-capacity=10000
traceusage.max-retries=3
traceusage.retry-delay-millis=1000
