spring.application.name=traceusage-demo-api
server.port=8081

traceusage.enabled=true
traceusage.endpoint=http://localhost:8080/api/v1/events
traceusage.batch-endpoint=http://localhost:8080/api/v1/events/batch
traceusage.api-key=tru_sk_O_lWsZ7a8g73SVUZvPnkOc9fJI3NS0lY2psFTbSXz9g
traceusage.batch-size=100
traceusage.max-retries=3
traceusage.retry-delay-millis=1000
