spring.application.name=traceusage-demo-api
server.port=8082

traceusage.enabled=true
traceusage.endpoint=http://localhost:8080/api/v1/events
traceusage.api-key=tru_sk_44ULDos6_aQIbbDZQqv9GmeUQDzuq3Ns2JWwsSJOPSc
